Vagrant.configure("2") do |config|

  num_instances = 3

  (1..num_instances).each do |i|
    config.vm.define "ubuntu#{i}" do |ubuntu|
      ubuntu.vm.box = "ubuntu/trusty64"
      ubuntu.vm.hostname = "ubuntu#{i}"
      ubuntu.vm.network "private_network", ip: "192.168.33.#{i + 100}"
      ubuntu.vm.provider "virtualbox" do |hv|
        hv.memory = "2048"
        hv.cpus = 2
      end
      ubuntu.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
      SHELL
    end
  end

end
